version: '3.8'

services:
  postgresql18_za:
    container_name: postgresql18_za
    image: docker.io/warkanum/postgresql18_za
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5403:5432"
    volumes:
      - /tmp/postgresql18_za_data:/var/lib/postgresql
    env_file:
      - .env
    restart: unless-stopped
    shm_size: 8g
    deploy:
      resources:
        limits:
          memory: 10G
          cpus: '4'
